//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASTHENIA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Object = new HashSet<Object>();
            this.Weapon = new HashSet<Weapon>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public long XP { get; set; }
        public long HP { get; set; }
        public long MaxHP { get; set; }
        public int Cell_ID { get; set; }
    
        public virtual Cell Cell { get; set; }
        public virtual ICollection<Object> Object { get; set; }
        public virtual ICollection<Weapon> Weapon { get; set; }
    }
}
