//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2NET_LIU_Yaning
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public Driver()
        {
            this.Trip = new HashSet<Trip>();
        }
    
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int Age { get; set; }
        public double Salary { get; set; }
    
        public virtual City City { get; set; }
        public virtual Campus Campus { get; set; }
        public virtual CarModel CarModel { get; set; }
        public virtual ICollection<Trip> Trip { get; set; }
    }
}
