//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASTHENIA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cell
    {
        public Cell()
        {
            this.Player = new HashSet<Player>();
        }
    
        public int ID { get; set; }
        public short PosX { get; set; }
        public short PosY { get; set; }
        public short MonsterRate { get; set; }
        public short MonsterGroup { get; set; }
        public bool CanMoveTo { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Player> Player { get; set; }
    }
}
