//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASTHENIA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RpgGamingEntities : DbContext
    {
        public RpgGamingEntities()
            : base("name=RpgGamingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cell> Cell { get; set; }
        public DbSet<Monster> Monster { get; set; }
        public DbSet<Object> Object { get; set; }
        public DbSet<ObjectType> ObjectType { get; set; }
        public DbSet<Player> Player { get; set; }
        public DbSet<Weapon> Weapon { get; set; }
    }
}
